# Prediction of Studens Dropout and academic success

A Project by
Cristal Rivera
Anton Donle

## 1. Problem Definition and dataset selection

Clearly define the problem statement by explaining its context and relevance.
* Justify the choice of dataset and discuss its potential to address the problem.

In [1]:
#Import Required Dependencies
import numpy as np
import pandas as pd
from sklearn.svm import SVC

In [2]:
#Load Dataset, seperate on ;
data = pd.read_csv('data.csv', sep = ';')

In [3]:
#look at data
data[0:100]

Marital status  Application mode  Application order  Course  \
0                1                17                  5     171   
1                1                15                  1    9254   
2                1                 1                  5    9070   
3                1                17                  2    9773   
4                2                39                  1    8014   
..             ...               ...                ...     ...   
95               1                15                  1    9119   
96               1                 1                  5    9773   
97               1                 1                  5    9500   
98               1                 1                  1    9085   
99               1                 1                  4    9500   

    Daytime/evening attendance\t  Previous qualification  \
0                              1                       1   
1                              1                       1   
2                              1                       1   
3                              1                       1   
4                              0                       1   
..                           ...                     ...   
95                             1                       1   
96                             1                       1   
97                             1                       1   
98                             1                       1   
99                             1                       1   

    Previous qualification (grade)  Nacionality  Mother's qualification  \
0                            122.0            1                      19   
1                            160.0            1                       1   
2                            122.0            1                      37   
3                            122.0            1                      38   
4                            100.0            1                      37   
..                             ...          ...                     ...   
95                           130.0           26                      38   
96                           135.0            1                      37   
97                           132.0            1                      37   
98                           135.0            1                       1   
99                           115.0            1                       3   

    Father's qualification  ...  Curricular units 2nd sem (credited)  \
0                       12  ...                                    0   
1                        3  ...                                    0   
2                       37  ...                                    0   
3                       37  ...                                    0   
4                       38  ...                                    0   
..                     ...  ...                                  ...   
95                       3  ...                                    0   
96                       1  ...                                    0   
97                      37  ...                                    0   
98                       2  ...                                    0   
99                       3  ...                                    0   

    Curricular units 2nd sem (enrolled)  \
0                                     0   
1                                     6   
2                                     6   
3                                     6   
4                                     6   
..                                  ...   
95                                    5   
96                                    6   
97                                    8   
98                                    5   
99                                    7   

    Curricular units 2nd sem (evaluations)  \
0                                        0   
1                                        6   
2                                        0   
3          

## 2. Exploratory Data Analysis

### 2.1 Correlation between Columns

In [4]:
#create new data frame without Target variable
data_without_target = data.drop(['Target'], axis = 1) 
#Make a correlation matrix
corr = data_without_target.corr()
corr.style.background_gradient(cmap='coolwarm')

We can see that there is a very big correlation between credits in the first and second semester (graded, evaluated and approved). <br>
We should maybe combine them into one or two categories (credits 1. sem, credits 2. sem)<br>
There is a very large correlation between nationality and International which makes sense and we should probably remove one of them.<br>
There is a large correlation between age and marital status + application mode<br>

In [5]:
#create data for curricular columns
curricular_data = data_without_target.filter(like ="Curricular", axis=1)

#Make a correlation matrix
corr = curricular_data.corr()
corr.style.background_gradient(cmap='coolwarm')

In [6]:
##Create correlation table with values and not a plot
correlation_matrix = data_without_target.corr()
# Remove self-correlation (set diagonal values to NaN)
np.fill_diagonal(correlation_matrix.values, np.nan)
#treshold to filter the confusion matrix with the correlations that are higher to this value
threshold = 0.5
# Find correlated pairs (without taking absolute values)
high_corr_pairs = correlation_matrix.stack().reset_index() #transform to a DF
high_corr_pairs.columns = ['Feature_1', 'Feature_2', 'Correlation']
# Filter to keep both high positive and high negative correlations
filtered_corr = high_corr_pairs[
    (high_corr_pairs['Correlation'] > threshold) | (high_corr_pairs['Correlation'] < -threshold)
].sort_values(by="Correlation", ascending=False)

# Display the results
filtered_corr[::2]

Feature_1  \
761              Curricular units 1st sem (credited)   
1002             Curricular units 2nd sem (enrolled)   
360                              Mother's occupation   
1074             Curricular units 2nd sem (approved)   
1110                Curricular units 2nd sem (grade)   
264                                      Nacionality   
1038          Curricular units 2nd sem (evaluations)   
756              Curricular units 1st sem (credited)   
862              Curricular units 1st sem (approved)   
1080             Curricular units 2nd sem (approved)   
967              Curricular units 2nd sem (credited)   
1004             Curricular units 2nd sem (enrolled)   
1078             Curricular units 2nd sem (approved)   
899                 Curricular units 1st sem (grade)   
870              Curricular units 1st sem (approved)   
827           Curricular units 1st sem (evaluations)   
972              Curricular units 2nd sem (credited)   
1072             Curricular units 2nd sem (approved)   
904                 Curricular units 1st sem (grade)   
762              Curricular units 1st sem (credited)   
758              Curricular units 1st sem (credited)   
832           Curricular units 1st sem (evaluations)   
866              Curricular units 1st sem (approved)   
1008             Curricular units 2nd sem (enrolled)   
1037          Curricular units 2nd sem (evaluations)   
1146  Curricular units 2nd sem (without evaluations)   
221                   Previous qualification (grade)   
826           Curricular units 1st sem (evaluations)   
868              Curricular units 1st sem (approved)   
288                           Mother's qualification   
665                                Age at enrollment   
828           Curricular units 1st sem (evaluations)   
968              Curricular units 2nd sem (credited)   
1077             Curricular units 2nd sem (approved)   
666                                Age at enrollment   

                                           Feature_2  Correlation  
761              Curricular units 2nd sem (credited)     0.944811  
1002             Curricular units 1st sem (enrolled)     0.942627  
360                              Father's occupation     0.910472  
1074             Curricular units 1st sem (approved)     0.904002  
1110                Curricular units 1st sem (grade)     0.837170  
264                                    International     0.790935  
1038          Curricular units 1st sem (evaluations)     0.778863  
756              Curricular units 1st sem (enrolled)     0.774344  
862              Curricular units 1st sem (enrolled)     0.769083  
1080                Curricular units 2nd sem (grade)     0.760804  
967              Curricular units 1st sem (enrolled)     0.753747  
1004             Curricular units 1st sem (approved)     0.733772  
1078             Curricular units 2nd sem (enrolled)     0.703258  
899              Curricular units 1st sem (approved)     0.696113  
870                 Curricular units 2nd sem (grade)     0.685560  
827              Curricular units 1st sem (enrolled)     0.680220  
972              Curricular units 2nd sem (enrolled)     0.676258  
1072             Curricular units 1st sem (enrolled)     0.673341  
904              Curricular units 2nd sem (approved)     0.673335  
762              Curricular units 2nd sem (enrolled)     0.644826  
758              Curricular units 1st sem (approved)     0.628394  
832              Curricular units 2nd sem (enrolled)     0.611842  
866              Curricular units 2nd sem (credited)     0.607661  
1008          Curricular units 2nd sem (evaluations)     0.604821  
1037             Curricular units 1st sem (enrolled)     0.599567  
1146  Curricular units 1st sem (without evaluations)     0.583261  
221                                  Admission grade     0.580444  
826              Curricular units 1st sem (credited)     0.542919  
868           Curricular units 2nd sem (evaluations)  

We saw there is a high correlation between the curricular columns. 

Based on this table we can see the variables that are correlated and that we can decide to either remove one of those or merge them like the curricular columns.

Interpreting Economic Indicators:

Unemployment Rate: Reflects the percentage of the labor force that is unemployed at the time of the student's enrollment. A higher unemployment rate might influence a student's decision to pursue higher education or affect their financial stability. Inflation Rate: Indicates the rate at which the general level of prices for goods and services is rising. High inflation can impact the cost of living and educational expenses. GDP (Gross Domestic Product): Represents the economic performance of the country. A higher GDP may correlate with better funding for educational institutions and more opportunities for students.#Review of the three external economic variables:



In [7]:
economic_var = data_without_target[['Unemployment rate','Inflation rate','GDP']]
economic_var

Unemployment rate  Inflation rate   GDP
0                  10.8             1.4  1.74
1                  13.9            -0.3  0.79
2                  10.8             1.4  1.74
3                   9.4            -0.8 -3.12
4                  13.9            -0.3  0.79
...                 ...             ...   ...
4419               15.5             2.8 -4.06
4420               11.1             0.6  2.02
4421               13.9            -0.3  0.79
4422                9.4            -0.8 -3.12
4423               12.7             3.7 -1.70

[4424 rows x 3 columns]

### 2.2. Target Variable

In [8]:
#Check for class balance
n_graduate, n_dropout, n_enrolled = data.value_counts('Target')

In [9]:
n = n_graduate + n_dropout + n_enrolled
proportion_g = n_graduate/n
proportion_d = n_dropout/n
proportion_e = n_enrolled/n
print(proportion_g, proportion_d, proportion_e)

0.4993218806509946 0.3212025316455696 0.1794755877034358


We observe the following pattern of our target label: <br>
Graduate: 2209 (0.49) <br>
Dropout: 1421 (0.32)<br>
Enrolled: 794 (0.17)<br>
First number is occurence, second is frequency
There is a class imbalance.

### 2.3. General Feature analysis

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   Marital status                                  4424 non-null   int64  
 1   Application mode                                4424 non-null   int64  
 2   Application order                               4424 non-null   int64  
 3   Course                                          4424 non-null   int64  
 4   Daytime/evening attendance	                     4424 non-null   int64  
 5   Previous qualification                          4424 non-null   int64  
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64  
 8   Mother's qualification                          4424 non-null   int64  
 9   Father's qualification                   

In [11]:
data.value_counts("International")

International
0    4314
1     110
Name: count, dtype: int64

In [12]:
data.value_counts("Nacionality")

Nacionality
1      4314
41       38
26       14
6        13
22       13
24        5
11        3
103       3
100       3
105       2
101       2
62        2
25        2
2         2
21        2
32        1
17        1
14        1
13        1
108       1
109       1
Name: count, dtype: int64

In [13]:
data.value_counts("Mother's qualification")

Mother's qualification
1     1069
37    1009
19     953
38     562
3      438
34     130
2       83
4       49
12      42
5       21
40       9
39       8
9        8
41       6
43       4
6        4
42       4
11       3
29       3
30       3
10       3
35       3
36       3
14       2
26       1
27       1
22       1
18       1
44       1
Name: count, dtype: int64

In [14]:
data.value_counts("Father's qualification")

Father's qualification
37    1209
19     968
1      904
38     702
3      282
34     112
2       68
4       39
12      38
39      20
5       18
11      10
36       8
9        5
40       5
30       4
14       4
22       4
29       3
41       2
43       2
35       2
26       2
10       2
6        2
33       1
31       1
27       1
25       1
20       1
18       1
13       1
42       1
44       1
Name: count, dtype: int64

### 2.4. Conclusion

1. Resolve Economic Situation (GPD, Inflation Rate, Unenmployment Rate)
2. Resolve International + Nationality
3. Maritial Status + Age of enrollment, Age of enrollment + application mode
4. Resolve Curricular units
5. Resolve Mothers + Fathers occupation
6. Replace numbers that encode something by string for what they encode
7. undo encoding

## 3. ML before Feature Engineering

In [15]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split    

from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes  import GaussianNB


In [16]:
#We will drop people with target value == Enrolled
enrolled = data[data["Target"] == "Enrolled"].index
data.drop(enrolled,inplace=True)
data["Target"].value_counts()

Target
Graduate    2209
Dropout     1421
Name: count, dtype: int64

In [17]:
data_before_engineering = data

#Define X and y 
X = data_before_engineering["Target"]
y = data_before_engineering.drop(['Target'], axis = 1) 

# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=42)

### 3.1. SVM

In [18]:
def train_and_predict_SVM(X_train, y_train, y_test):
    #Initilize a SVM
    clf = SVC(random_state=42)
    #Fit it to the training data
    clf.fit(y_train,X_train) 
    #Predicate on the testdata
    x_pred = clf.predict(y_test)
    return(x_pred)

In [19]:
x_pred = train_and_predict_SVM(X_train, y_train, y_test)
acc = accuracy_score(X_test, x_pred)
print(acc)
confusion_matrix(X_test, x_pred)

0.6211453744493393


array([[  0, 344],
       [  0, 564]], dtype=int64)

### 3.2. KNN

In [20]:
def train_and_predict_KNN(X_train, y_train, y_test, n):
    #Initilize a KNN
    knn = KNeighborsClassifier(n_neighbors=n)
    #Fit it to the training data
    knn.fit(y_train,X_train) 
    #Predicate on the testdata
    x_pred = knn.predict(y_test)
    #Check Accuracy
    return(x_pred)

In [21]:
n = 3
x_pred= train_and_predict_KNN(X_train, y_train, y_test, n)
acc = accuracy_score(X_test, x_pred)
print(acc)
confusion_matrix(X_test, x_pred)

0.7731277533039648


array([[213, 131],
       [ 75, 489]], dtype=int64)

### 3.3. Logistic Regression

In [22]:
def train_and_predict_LR(X_train, y_train, y_test):
    #Initilize a LR
    clf = LogisticRegression(random_state=42,max_iter = 50)
    #Fit it to the training data
    clf.fit(y_train,X_train) 
    #Predicate on the testdata
    x_pred = clf.predict(y_test)
    return x_pred

In [23]:
x_pred = train_and_predict_LR(X_train, y_train, y_test)
acc = accuracy_score(X_test, x_pred)
print(acc)
print(confusion_matrix(X_test, x_pred))

0.8072687224669604
[[234 110]
 [ 65 499]]


C:\Users\tosch\miniconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### 3.4. Decision Trees

In [24]:
from sklearn.tree import DecisionTreeClassifier


def train_and_predict_DTC(X_train, y_train, y_test):

    #Initilize a DTC
    clf = DecisionTreeClassifier(random_state=42)
    #Fit it to the training data
    clf.fit(y_train,X_train) 
    #Predicate on the testdata
    x_pred = clf.predict(y_test)
    return x_pred

In [36]:
x_pred = train_and_predict_DTC(X_train, y_train, y_test)
acc = accuracy_score(X_test, x_pred)
print(acc)
print(confusion_matrix(X_test, x_pred))

0.8513215859030837
[[276  68]
 [ 67 497]]


### 3.5. Naive Bayes

In [31]:
def train_and_predict_GNB(X_train, y_train, y_test):
    #Initilize a SVM
    gnb = GaussianNB()
    #Fit it to the training data
    gnb.fit(y_train,X_train) 
    #Predicate on the testdata
    x_pred = gnb.predict(y_test)
    #Check Accuracy
    accuracy = accuracy_score(x_pred, X_test)
    return x_pred

In [34]:
x_pred = train_and_predict_GNB(X_train, y_train, y_test)
acc = accuracy_score(X_test, x_pred)
print(acc)
print(confusion_matrix(X_test, x_pred))

0.8425110132158591
[[249  95]
 [ 48 516]]


## 4. Feature Engineering

In [28]:
#Translate Target to 0 or 1 for SVM 
#data.replace("Dropout", 0)
#data.replace("Graduate", 1)
""

''

Since Admission grade and previous qualification(grade) have high correlation -> Remove previous qualification(grade) <br>
Age at enrollment + Appplication mode -> Remove Application Mode <br>
Age at enrollment + Maritial Status -> Remove Maritial Status <br>
Join Curricular Units first and second semester for each category -> maybe further remove approved/enrolled <br>
International + Nationality -> Remove Nationality<br>
Mothers Occupation and Fathers Occupation -> Remove Fathers Occupation<br>
Mothers Education and Fathers Edducation -> Remove Fathers Education<br>


Course + Daytime/evening -> Remove Daytime/evening (Maybe dont because its only a slight negative correlation)<br>


In [29]:
#Here we will remove the previously mentioned columns
data.drop(columns = ["Previous qualification (grade)", "Marital status", "Nacionality", "Father's qualification", "Father's occupation"], inplace = True)

In [30]:
#Here we will join the curricular units
#Get the average of the credits columns of 1st sem and 2nd sem

# categories of name:

data['Curricular units year (credited)'] = (data['Curricular units 1st sem (credited)'] + data['Curricular units 2nd sem (credited)'])/2
data['Curricular units year (enrolled)'] = (data['Curricular units 1st sem (enrolled)'] + data['Curricular units 2nd sem (enrolled)'])/2
data['Curricular units year (evaluations)'] = (data['Curricular units 1st sem (evaluations)'] + data['Curricular units 2nd sem (evaluations)'])/2
data['Curricular units year (approved)'] = (data['Curricular units 1st sem (approved)'] + data['Curricular units 2nd sem (approved)'])/2
data['Curricular units year (grade)'] = (data['Curricular units 1st sem (grade)'] + data['Curricular units 2nd sem (grade)'])/2
data['Curricular units year (without evaluations)'] = (data['Curricular units 1st sem (without evaluations)'] + data['Curricular units 2nd sem (without evaluations)'])/2

data.drop(columns = ['Curricular units 1st sem (credited)','Curricular units 2nd sem (credited)','Curricular units 1st sem (enrolled)','Curricular units 2nd sem (enrolled)','Curricular units 1st sem (evaluations)','Curricular units 2nd sem (evaluations)',
                 'Curricular units 1st sem (approved)','Curricular units 2nd sem (approved)','Curricular units 1st sem (grade)','Curricular units 2nd sem (grade)','Curricular units 1st sem (without evaluations)','Curricular units 2nd sem (without evaluations)'], inplace = True)

## 5 Machine Learning after Engineering

## 6. Evaluation & Interpretation

## 7. Conclusion